# source: https://github.com/pandas-dev/pandas/blob/cb6859249d93dee7231d56bb3c2eb103ba2d97d0/.github/workflows/assign.yml

name: Assign
on:
  issue_comment:
    types: [created, edited]

jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - name:
        run: |
            if [[ "${{ github.event.comment.body }}" == ".take" ]]; then
                echo "Assigning issue ${{ github.event.issue.number }} to ${{ github.event.comment.user.login }}"
                curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -d '{"assignees": ["${{ github.event.comment.user.login }}"]}' https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/assignees
            fi
