name: Auto merge Dependabot
on: pull_request

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
    - name: Only do this when dependabot
      if: contains(github.ref, 'dependabot')
      run: echo "Hello ref ${{ github.ref }}"
    - name: automerge
      uses: bdougie/automerge-action@bot
      if: github.event.check_suite.app.name == 'Netlify' && github.event.check_suite.conclusion == 'success'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
