name: Node CI/CD

on: 
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: 🛠 BUILD
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Cache node modules
      uses: actions/cache@v2
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install and test
      run: |
        npm ci
        npm test
      env:
        CI: true
    
  release: 
    name: 💍 Semantic Release

    needs: [build]
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: set git user
        run: |
          git config --global user.name ${GITHUB_ACTOR}
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: npm install and test
        run: |
          npm install
      - name: Release
        run: |
          npm run release
          git push --follow-tags origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
