name: Node CI/CD

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: 🛠 BUILD
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v2.1.5
      with:
        node-version: '14.x'

    - name: Install npm@7
      run: npm i -g npm@7

    - name: Build and test
      run: |
        npm ci
        npm audit --production
        npm test

    - name: Release
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
        git config --global user.name ${GITHUB_ACTOR}
        git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        npm run release
        git push --follow-tags origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docusaurus:
    name: 📖 Documentation
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    needs: [ build ]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install npm@7
        run: npm i -g npm@7

      - name: npm install and test
        run: |
          cd docs
          npm ci --production
          npm run build

      - name: Deploy to static branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          commit_message: ${{ github.event.head_commit.message }}
          enable_jekyll: false
          cname: docs.opensauced.pizza
