on:
  push:
    branches:
     - main
    paths: ["stories/**", "src/components/**"]

name: Publish stories if changed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: "☁️ checkout repository"
      uses: actions/checkout@v2

    - name: "🔧 setup node"
      uses: actions/setup-node@v2.1.5
      with:
        node-version: 16

    - name: "🔧 install npm@latest"
      run: npm i -g npm@latest

    - name: "📦 install dependencies"
      run: npm ci

    - name: "📦 build Storybook"
      run:  npm run build-storybook

    - name: Build and deploy to storybook-static branch
      uses: JamesIves/github-pages-deploy-action@3.4.8
      with:
        ACCESS_TOKEN: ${{ secrets.BDOUGIE_TOKEN }}
        BRANCH: storybook-static
        FOLDER: storybook-static
